[versions]
blossom = '1.3.1'
shadow = '8.1.7'
spotless = '6.25.0'
loom = '1.7-SNAPSHOT'
forgegradle = '[6.0,6.2)'
neogradle = '7.0.151'
mixin = '0.7-SNAPSHOT'
spongegradle = '2.2.0'
vanillagradle = '0.2.1-SNAPSHOT'
unimined = '1.3.3'

[plugins]
blossom = { id = 'net.kyori.blossom', version.ref = 'blossom' }
shadow = { id = 'io.github.goooler.shadow', version.ref = 'shadow' }
spotless = { id = 'com.diffplug.spotless', version.ref = 'spotless' }
loom = { id = 'fabric-loom', version.ref = 'loom' }
legacyloom = { id = 'legacy-looming', version.ref = 'loom' }
forgegradle = { id = 'net.minecraftforge.gradle', version.ref = 'forgegradle' }
neogradle = { id = 'net.neoforged.gradle.userdev', version.ref = 'neogradle' }
mixin = { id = 'org.spongepowered.mixin', version.ref = 'mixin' }
spongegradle = { id = 'org.spongepowered.gradle.plugin', version.ref = 'spongegradle' }
vanillagradle = { id = 'org.spongepowered.gradle.vanilla', version.ref = 'vanillagradle' }
unimined = { id = 'xyz.wagyourtail.unimined', version.ref = 'unimined' }
