name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group_id}.${project_id}.platforms.BukkitPlugin'
depend: [ TaterLib, ProtocolLib ]
depends: [ TaterLib, ProtocolLib ]
softdepends: [ ]
folia-supported: true
